(() => {
'use strict';
const $=id=>document.getElementById(id), viewport=$('viewport'), camera=$('camera'), player=$('player');
const state={x:1110,y:880,zoom:1,drag:false,last:null,keys:new Set(),xp:0,discovered:[],active:'hub',target:null};
const zones={hub:{name:'INFO CORE',sub:'CENTRAL DISTRICT',level:1,skill:null,x:1110,y:760,text:'Сердце города. Здесь соединяются все маршруты обучения.',lesson:'Выбери направление и начни исследование.'},python:{name:'PYTHON DISTRICT',sub:'CODE CAMPUS',level:1,skill:'Python',x:590,y:550,text:'Кампус, где код превращается в работающие программы.',lesson:'print("Hello, world!")\n\nПервая программа уже меняет состояние мира.'},algo:{name:'ALGORITHM CITY',sub:'LOGIC METRO',level:2,skill:'Алгоритмы',x:1080,y:310,text:'Город, в котором дороги и узлы работают как алгоритмы.',lesson:'ЕСЛИ условие истинно → путь A\nИНАЧЕ → путь B\n\nВыбери маршрут решения.'},ai:{name:'AI LAB',sub:'NEURAL RESEARCH',level:3,skill:'AI',x:1730,y:560,text:'Исследовательский комплекс нейросетей, данных и моделей.',lesson:'ДАННЫЕ → МОДЕЛЬ → ПРОВЕРКА → РЕЗУЛЬТАТ\n\nAI — это процесс, а не магия.'},web:{name:'WEB LAB',sub:'CREATOR TOWERS',level:2,skill:'Web',x:1810,y:1140,text:'Высотный район, где интерфейсы, браузеры и серверы становятся частью архитектуры.',lesson:'HTML = структура\nCSS = внешний вид\nJavaScript = поведение'},exam:{name:'EXAM ARENA',sub:'CHALLENGE ZONE',level:4,skill:'Экзамен',x:520,y:1190,text:'Арена испытаний. Здесь знания проверяются под давлением времени.',lesson:'РЕЖИМ ИСПЫТАНИЯ\n01 — анализ условия\n02 — решение\n03 — проверка'}};
const npcs={byte:{name:'BYTE',text:'Начни с Python. Небольшие программы — лучший вход в большой мир.'},ada:{name:'ADA',text:'Данные сами по себе ничего не решают. Важно понять, какую модель ты строишь.'},max:{name:'MAX',text:'Создавай проекты. Теория без результата быстро забывается.'}};
function save(){localStorage.setItem('info-world-next',JSON.stringify({xp:state.xp,discovered:state.discovered}));$('saveText').textContent='SYNCED'}function load(){try{Object.assign(state,JSON.parse(localStorage.getItem('info-world-next')||'{}'))}catch(e){}}
function unlocked(id){return id==='hub'||zones[id].level<=1||state.discovered.includes('python')&&zones[id].level<=2||state.discovered.includes('algo')&&zones[id].level<=3||state.discovered.includes('ai')&&zones[id].level<=4}
function update(){const z=zones[state.active]||zones.hub;$('placeName').textContent=z.name;$('placeSub').textContent=z.sub;$('xpNum').textContent=state.xp;$('levelNum').textContent=1+Math.floor(state.xp/100);$('xpBar').style.width=(state.xp%100)+'%';$('discoverCount').textContent=state.discovered.length;$('discoverBar').style.width=(state.discovered.length/5*100)+'%';$('missionTitle').textContent=state.discovered.length===5?'Исследование завершено':'Открыть следующий район';$('missionText').textContent=state.discovered.length===5?'Теперь город полностью доступен.':'Подойди к тематической локации и нажми E.';document.querySelectorAll('.district-btn').forEach(b=>b.classList.toggle('active',b.dataset.id===state.active));document.querySelectorAll('.district-btn').forEach(b=>b.classList.toggle('locked',!unlocked(b.dataset.id)))}
function nav(){const n=$('districtNav');n.innerHTML='';for(const id of ['python','algo','ai','web','exam']){const z=zones[id],b=document.createElement('button');b.className='district-btn';b.dataset.id=id;b.innerHTML=`<span>${z.name}</span><small>${unlocked(id)?'OPEN':'LV '+z.level}</small>`;b.onclick=()=>{if(!unlocked(id))return toast('Район пока закрыт');focus(id)};n.appendChild(b)}}
function transform(){camera.style.transform=`translate(${(state.camX||0)}px,${(state.camY||0)}px) scale(${state.zoom})`;player.setAttribute('transform',`translate(${state.x} ${state.y})`);$('zoomLabel').textContent=Math.round(state.zoom*100)+'%'}
function focus(id){const z=zones[id];state.active=id;state.target=id;state.camX=(1110-z.x)*.38;state.camY=(760-z.y)*.38;transform();update();setTimeout(()=>openZone(id),350)}
function openZone(id){const z=zones[id];if(!unlocked(id))return toast('Сначала открой предыдущий маршрут');state.active=id;$('modalEyebrow').textContent=z.sub;$('modalTitle').textContent=z.name;$('modalText').textContent=z.text;$('modalLesson').textContent=z.lesson;const done=state.discovered.includes(id);$('completeBtn').textContent=done?'Локация уже исследована':'Исследовать локацию';$('completeBtn').classList.toggle('done',done);$('modal').classList.remove('hidden');update()}
function complete(){const id=state.active;if(id==='hub'){$('modal').classList.add('hidden');return}if(!state.discovered.includes(id)){state.discovered.push(id);state.xp+=25;save();toast(`Открытие: ${zones[id].name} +25 XP`)}$('modal').classList.add('hidden');nav();update()}
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2400)}
function nearest(){let best=null,d=1e9;for(const [id,z] of Object.entries(zones)){const dd=Math.hypot(state.x-z.x,state.y-z.y);if(dd<d){d=dd;best=id}}return {id:best,d}}
function loop(){let dx=0,dy=0;if(state.keys.has('KeyW')||state.keys.has('ArrowUp'))dy-=1;if(state.keys.has('KeyS')||state.keys.has('ArrowDown'))dy+=1;if(state.keys.has('KeyA')||state.keys.has('ArrowLeft'))dx-=1;if(state.keys.has('KeyD')||state.keys.has('ArrowRight'))dx+=1;if(dx||dy){const l=Math.hypot(dx,dy);state.x=Math.max(50,Math.min(2150,state.x+dx/l*3.4));state.y=Math.max(50,Math.min(1400,state.y+dy/l*3.4));const n=nearest();state.active=n.d<105?n.id:'hub';$('interactionHint').classList.toggle('hidden',n.d>=105);transform();update()}requestAnimationFrame(loop)}
function stars(){const g=$('stars');let s='';for(let i=0;i<130;i++){const x=(i*137)%2200,y=(i*83)%900,r=i%7===0?2:1;s+=`<circle cx="${x}" cy="${y}" r="${r}" fill="#bcecff" opacity="${.12+(i%5)*.08}"/>`}g.innerHTML=s}
function boot(){let p=0;const timer=setInterval(()=>{p=Math.min(100,p+Math.floor(Math.random()*9)+4);$('loadBar').style.width=p+'%';$('loadPct').textContent=p+'%';if(p>=100){clearInterval(timer);$('enterBtn').disabled=false}},70);$('enterBtn').onclick=()=>{$('boot').classList.add('hidden');$('app').classList.remove('hidden')}}
load();stars();nav();update();transform();boot();setInterval(()=>{$('clock').textContent=new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})},1000);
document.addEventListener('keydown',e=>{if(['KeyW','KeyA','KeyS','KeyD','KeyE','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='KeyE'){const n=nearest();if(n.d<115)openZone(n.id);return}state.keys.add(e.code)});document.addEventListener('keyup',e=>state.keys.delete(e.code));
viewport.addEventListener('pointerdown',e=>{if(e.target.closest('.district-art')||e.target.closest('.npc'))return;state.drag=true;state.last={x:e.clientX,y:e.clientY};viewport.classList.add('dragging');viewport.setPointerCapture(e.pointerId)});viewport.addEventListener('pointermove',e=>{if(!state.drag)return;state.camX=(state.camX||0)+(e.clientX-state.last.x);state.camY=(state.camY||0)+(e.clientY-state.last.y);state.last={x:e.clientX,y:e.clientY};transform()});viewport.addEventListener('pointerup',()=>{state.drag=false;viewport.classList.remove('dragging')});viewport.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.72,Math.min(1.65,state.zoom+(e.deltaY<0?.08:-.08)));transform()},{passive:false});
document.querySelectorAll('.district-art').forEach(el=>el.addEventListener('click',()=>focus(el.dataset.zone)));document.querySelectorAll('.npc').forEach(el=>el.addEventListener('click',()=>toast(npcs[el.dataset.npc].name+': '+npcs[el.dataset.npc].text)));
$('zoomIn').onclick=()=>{state.zoom=Math.min(1.65,state.zoom+.1);transform()};$('zoomOut').onclick=()=>{state.zoom=Math.max(.72,state.zoom-.1);transform()};$('centerBtn').onclick=$('homeBtn').onclick=()=>{state.camX=0;state.camY=0;state.zoom=1;transform();toast('Камера возвращена в центр')};$('focusBtn').onclick=()=>{const next=['python','algo','web','ai','exam'].find(id=>!state.discovered.includes(id)&&unlocked(id))||'hub';focus(next)};$('helpBtn').onclick=()=>toast('WASD — движение • E — взаимодействие • мышь — камера');$('resetBtn').onclick=()=>{if(confirm('Сбросить прогресс города?')){localStorage.removeItem('info-world-next');location.reload()}};$('closeModal').onclick=()=>$('modal').classList.add('hidden');$('completeBtn').onclick=complete;
loop();
})();
